echo "Hello World!"


CREATE TABLE EMPLOYES

(
EMPLOYE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20 Byte),
LAST_NAME VARCHAR2(25 Byte),
EMAIL VARCHAR2(25 Byte),
PHONE_NUMBER VARCHAR2(20 Byte),
HIRE_DATE DATE,
JOB_ID VARCHAR2(10 Byte),
SALARY NUMBER(8,2)not null,
COMMISION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTAMENT_ID NUMBER(4)
)

